//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINIMVCPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogsTable
    {
        public int BlogId { get; set; }
        public string Images { get; set; }
        public string Messages { get; set; }
        public int UId { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
