//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuetionBankApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuetionTable
    {
        public int QuetionId { get; set; }
        public string Quetion { get; set; }
        public string Keyword { get; set; }
        public string SubjectType { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }

        public string SearchKeyword { get; set; }
    
        public virtual SubjectTable SubjectTable { get; set; }
    }
}
